name: brenoacf Blog
description: Blog sobre desenvolvimento, engenharia e outras coisas :-)
meta_description: "brenoacf Blog, blog sobre desenvolvimento, engenharia e outras coisas"

markdown: kramdown
highlighter: rouge 

logo: false
plugins:
    - jekyll-paginate
paginate: 15
baseurl: /
domain_name: ''
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://brenoacf.github.io'
author:         'Breno Augusto Cruz Faria'
